homeassistant:
  customize: !include customize.yaml
  # Name of the location where Home Assistant is running
  
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 58.371200
  longitude: 13.832150
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 300
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:
        
# Discover some devices automatically
discovery:
  enable:
    - homekit
homekit:
  filter:
    include_domains:
      - climate
      - light
      - sensor
# Allows you to issue voice commands from the frontend in enabled browsers
climate:
  - platform: melcloud
    email: danieltomasjohansson@gmail.com
    password: Morransmor88!
    
  - platform: mqtt
    name: "Värmepump Källare"
    optimistic: false
    retain: false
    qos: 0
    payload_on: 1
    payload_off: 0
    modes:
      - auto
      - heat
      - 'off'
    mode_state_topic: "emon/PID/Mode" 
    mode_command_topic: "emon/PID/changeMode"
    mode_state_template: >-
      {% if value == 0 %}
      auto
      {% elif value == 1 %}
      heat
      {% elif value == 2 %}
      'off'
      {% endif %}
    current_temperature_topic: "emon/PID/temperature2"
    min_temp: 17
    max_temp: 28
    temperature_state_topic: "emon/PID/setPoint"
    temperature_command_topic: "emon/PID/changePoint"

    
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: mqtt
    name: "room_temp"
    friendly_name: "Rumstemperatur"
    device_class: temperature
    state_topic: "emon/PID/temperature2"
  - platform: mqtt  
    name: "set_temp"
    friendly_name: "Inställd Temperatur"
    state_topic: "emon/PID/setPoint"

    
  - platform: yr

# Text to speech
tts:
  platform: google
  
mqtt:
  broker: 192.168.2.6
  port: 1883
  username: emonpi
  password: emonpimqtt2016
  
mqtt_statestream:
  base_topic: emon/PID/
  include:
    domains:
      - sensor