version: '2'
volumes:
    app1-data:
services:
  homeassistant:
    build: ./homeassistant
    container_name: homeassistant
    restart: always
    network_mode: host
    volumes:
      - app1-data:/config
