version: '2'
volumes:
  hass-config:
  unifi-cert:
  unifi-data:
  unifi-logs:
  
services:
  homeassistant:
    build: ./homeassistant
    container_name: homeassistant
    restart: always
    network_mode: host
    volumes:
      - hass-config:/config
  unifi:
    build: ./unifi
    container_name: unifi
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 3478:3478/udp
      - 8080:8080
      - 8443:8443
      - 8880:8880
      - 8843:8843
    volumes:
      - unifi-cert:/usr/lib/unifi/cert
      - unifi-data:/usr/lib/unifi/data
      - unifi-logs:/usr/lib/unifi/logs
    environment:
      - TZ=UTC