version: '2'

services:
  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:latest
    container_name: homeassistant
    restart: always
    network_mode: host
    volumes:
      - /opt/home_assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /media/usbstick/container/ssl:/ssl