version: '2'
volumes:
    hass-data1:
services:
  homeassistant:
    build: ./homeassistant
    container_name: homeassistant
    restart: always
    network_mode: host
    volumes:
      - hass-data1:/data
