version: '2'
volumes:
    hass-config:
services:
  homeassistant:
    build: ./homeassistant
    container_name: homeassistant
    restart: always
    network_mode: host
    volumes:
      - hass-config:/config