version: '2'
volumes:
    balena-data:
configs:
  myconfigfile:
  file: ./configuration.yaml
services:
  homeassistant:
    build: ./homeassistant
    container_name: homeassistant
    restart: always
    network_mode: host
    volumes:
      - balena-data:/config
    configs:
      - source: myconfigfile
        target: /config/configuration.yaml   
