version: '2'
volumes:
    balena-data:

services:
  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:latest
    container_name: homeassistant
    restart: always
    network_mode: host
    volumes:
      - balena-data:/config