version: '2'
volumes:
    balena-data:
services:
  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant
    container_name: homeassistant
    restart: always
    network_mode: host
    volumes:
      - balena-data:/config
  unifi:
    image: linuxserver/unifi
    container_name: unifi
    restart: always
    network_mode: host
    volumes:
      - balena-data:/data