FROM homeassistant/raspberrypi3-homeassistant:latest
ADD custom_components /config/custom_components
ADD custom_components/climite /config/custom_components/climite
VOLUME /config/custom_components/climate